name: libretrack
base: core22
version: 1.6.1
license: GPL-3.0-or-later
summary: Private, cross-platform package tracking app.
description: |
  Track postal items directly on your device using accounts of postal services. The app respects your privacy and freedom: you don't use third-party online services.

  📋 Features
  * Free and Open Source software (FOSS)
  * Support for various platforms and devices
  * Support accounts of different carriers
  * Detailed information about the postal items, carriers, tracking history
  * Local push notifications
  * Automatic tracking in the background, and also manual refreshing
  * Ability to add a list of track numbers
  * Filter and sort numbers by activity date, package status, carrier, etc
  * Barcode and QR code scanner for tracking numbers
  * Barcode generator
  * Archiving tracking numbers
  * Material Design 2.0
  * Night theme
  * Responsive UI for different devices form factors

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  libretrack:
    extensions: [gnome]
    command: libretrack
    plugs:
      - network
      - home

parts:
  libretrack:
    plugin: flutter
    source: https://github.com/proninyaroslav/libretrack.git
    source-tag: 1.6.1
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libappindicator3-dev
      - gettext
    stage-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libappindicator3-dev
      - libsqlite3-dev
