name: Flutter Build CI

# TODO: For test
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '2.2.x'
    - name: Disable Google Analytics
      run: flutter config --no-analytics
    - name: Install dependencies
      run: flutter pub get
    - name: Enable desktop support
      run: flutter config --enable-linux-desktop
    - name: Build debug Android APK
      run: flutter build apk --flavor main --debug
    - name: Build debug Linux binary
      run: flutter build linux --debug
