name: Flutter Release Build CI

# on:
#   push:
#     tags:
#     - '*'
# TODO: for test
on: [push]

jobs:
  build-linux-x86_64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '2.2.x'
    - name: Disable Google Analytics
      run: flutter config --no-analytics
    - name: Install dependencies
      run: flutter pub get
    - name: Enable Linux support
      run: flutter config --enable-linux-desktop
    - name: Install dependencies
      run: sudo apt update && sudo apt install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libjsoncpp1 libsecret-1-dev libsecret-1-0 librhash0 libsqlite3-dev libappindicator3-dev gettext -y
    - name: Build
      run: flutter build linux --release
    - name: Publish draft release
      uses: ncipollo/release-action@v1
      run: |
        cd build/linux/x64/release/bundle
        tar -czf ../libretrack-${{ env.RELEASE_VERSION }}-linux-x86_64.tar.gz *
      with:
        draft: true
        artifacts: build/linux/x64/release/*.tar.gz

  build-linux-arm64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0
    - uses: uraimo/run-on-arch-action@v2.1.1
      with:
        flutter-version: '2.2.x'
        arch: arm64
    - name: Disable Google Analytics
      run: flutter config --no-analytics
    - name: Install dependencies
      run: flutter pub get
    - name: Enable Linux support
      run: flutter config --enable-linux-desktop
    - name: Install dependencies
      run: sudo apt update && sudo apt install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libjsoncpp1 libsecret-1-dev libsecret-1-0 librhash0 libsqlite3-dev libappindicator3-dev gettext -y
    - name: Build
      run: flutter build linux --release
    - name: Publish draft release
      uses: ncipollo/release-action@v1
      run: |
        cd build/linux/arm64/release/bundle
        tar -czf ../libretrack-${{ env.RELEASE_VERSION }}-linux-arm64.tar.gz *
      with:
        draft: true
        artifacts: build/linux/arm64/release/*.tar.gz
